# Generated by Django 3.1.4 on 2020-12-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_input',
            field=models.BooleanField(default=False, verbose_name='Является полем ввода'),
        ),
        migrations.AlterField(
            model_name='question',
            name='right_answers',
            field=models.ManyToManyField(blank=True, related_name='questions', to='quiz.Answer', verbose_name='Правильные ответы'),
        ),
    ]
