# Generated by Django 3.1.4 on 2020-12-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201223_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание викторины'),
        ),
    ]
